name: Android Release

# 1
on:
  # 2
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" ]

  # 3
  workflow_dispatch:

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      # 10  
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.7.7"
          channel: 'stable'
      # 12
      - name: Get dependencies
        run: flutter pub get



      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build appbundle
        
    
      - name: Convert aab to apk
        id: convert_aab
        uses: mukeshsolanki/bundletool-action@v1.0.0
        with:
         aabFile: build/app/outputs/bundle/release/app-release.aab
         base64Keystore: ${{ secrets.KEYSTORE_FILE }}
         keystorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
         keystoreAlias: ${{ secrets.KEY_ALIAS }}
         keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
         bundletoolVersion: '1.9.0'

      - uses: actions/upload-artifact@v3
        with:
         name: ${{github.run_number}}release-apk
         path: ${{ steps.convert_aab.outputs.apkPath }}


      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
